### PR TITLE
Quick fixes

### PR DESCRIPTION
**Pull request by EliteTK**
Here are some quick fixes I found while trying to work out why the game gets a segfault when exiting. I haven't quite tracked that down but it doesn't affect things right now.

### CODE REVIEW

**Comment by EliteTK** [comment]
I might have more things to add to this tomorrow, I'm not sure what happens when a branch is merged and I add more commits to it, but for now, leave this open please.

**Comment by EliteTK** [comment]
@dean1012 Feel free to merge this if you're happy with it. I think it's best if I keep the stream of clean-up and maintenance patches moving along instead of trying to batch them up because otherwise the patches will end up with a lot of merge conflicts.

I'm going through my copy of A Tour of C++ (by Bjarne Stroustrup) and applying what is written there to the project, but it's not going to be something I can do all at once so I'll keep submitting patches like these while working on other things.

**Comment by dean1012** [comment]
I get a crash when exiting the game every time. Specifically, seems to be complaining about a call to al_destroy_bitmap(NULL) which leads me to believe that somewhere we are trying to destroy a bitmap that already has been destroyed.

I tried doing some simple debugging but was unable to pinpoint the issue more specifically than that. I'm also not sure if this bug was preexisting or part of this pull request so I'm not merging until you've had a chance to take a look.

**Comment by EliteTK** [comment]
Probably this is caused by a Card being copied.

But this problem would have exhibited itself before since we have no copy constructor.

I'll look into it tomorrow.

If all else fails I'll write a class to wrap ALLEGRO_BITMAP which implements copying and move semantics so that we can use it inside Card without Card itself needing to deal with copying and move semantics (responsibility is delegated to the single class).

That might be a better solution overall.

**Comment by dean1012** [comment]
Still getting the crash. See http://i.imgur.com/zbEODYA.png

I am not getting this in my branches though.

**Comment by EliteTK** [comment]
@dean1012 try now.

Valgrind gives me a clean slate (once I ignore all the darn DRI write errors which it incorrectly reports).

**Comment by dean1012** [comment]
It looks good and doesn't seem to crash on me any longer. However, it is complaining of merge conflicts.

I was afraid this might happen as I had to do a lot of finangling to get my other branch (flexible-assets) to merge. I was hoping it wouldn't propagate down the chain.

At any rate, can you try a pull/rebase or whatever and see if you can get it to resolve?

**Comment by EliteTK** [comment]
@dean1012 Darn, you appear to have replaced all tabs with four spaces in 97ad1c45296b57ee7fe31234c226035e08b17401. This has created quite a merging mess. In the future, I heavily suggest you avoid running auto-formatting tools on source like this.

**Comment by EliteTK** [comment]
@dean1012 Ok, the set comes with three revert commits to revert your style changes (which appar to have been causing you problems as well). The commits only revert style changes but keep source changes.

I highly recommend that you configure visual studio to stop automatically formatting your source files, automatic formatting does not work well with existing projects.

I think the game manager pull request might be using some mix of styles too. Once it is ready, I can help remove merge conflicts in it, I'll take the patchset, modify it so it works against my reverts and publish it as a new pull request (@brettschalin's changes will still be marked as his, so he won't lose out on contributing).

**Comment by dean1012** [comment]
Whoops. My bad. This wasn't intentional or rather my secondary computer had different settings than the primary. Thanks for reverting.

I'll merge this at the hotel tonight after testing. For now I have a flight to catch.

In regards to formatting I'll ensure this is disabled on the secondary computer as well at the hotel.

**Comment by dean1012** [comment]
I can't get this to compile. Complains about unique_ptr in main.cpp (missing memory include?)

Also complains about constructors for player1hand/player2hand and complains about the use of to_string in card.cpp.

**Comment by EliteTK** [comment]
Can you give specific details about the complaints? I can't recreate any warnings or errors with GCC even using -Wpedantic.

Regarding the unique_ptr thing in main.cpp, have you tried including <memory> to see if it goes away (looks like my libstdc++ probably includes <memory> through another header file that I have included).

**Comment by dean1012** [comment]
I apologize. Class this week has me busy and my wife also traveled with me which is rare. I'll get back to this as soon as I'm able. I don't want to merge until we know for sure it will continue to work on Windows. 

I'm unfortunately aware that the failure to merge this right now may prevent others from working on the project at the moment.

**Comment by dean1012** [comment]
Ok so I finally had a few moments to look at this...

Go to Card.cpp and add an include for the <string> header

Once you do this, it seems to compile. I'll test again and merge once you've done this.

**Comment by dean1012** [comment]
@EliteTK pinging you just in case you missed the previous notification. I think you just need to add an include on the top of Card.cpp for the \<string\> header

**Comment by EliteTK** [comment]
I'll get to this this afternoon. I missed the notifications.

**Comment by EliteTK** [comment]
There you go. Sorry about the delays.

**Comment by dean1012** [comment]
Works. no problem. I'm busy too. Merging.

**Pull request merged**
